In [1]:
import numpy as np
import pandas as pd

In [2]:
# change dir to Google Drive
path = "./drive/MyDrive/Colab Notebooks/TechGig Hackathon_202205/"
import os
os.chdir(path)
!pwd

/content/drive/MyDrive/Colab Notebooks/TechGig Hackathon_202205


In [3]:
# load datasets
ph_tr = pd.read_csv("./Phising_Training_Dataset.csv")
ph_te = pd.read_csv("./Phising_Testing_Dataset.csv")

print(ph_tr.shape)
print(ph_te.shape)

ph_tr.head()
ph_te.head()

(8955, 32)
(2100, 31)


key  having_IP  URL_Length  Shortining_Service  having_At_Symbol  \
0  21338          1           1                   1                 1   
1  21339          1          -1                   1                 1   
2  21340          1          -1                   1                 1   
3  21341         -1          -1                  -1                 1   
4  21342          1          -1                   1                 1   

   double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  SSLfinal_State  \
0                         1              1                 -1               1   
1                         1             -1                  0              -1   
2                         1             -1                  0               0   
3                        -1             -1                 -1              -1   
4                         1             -1                  1               1   

   Domain_registeration_length  ...  RightClick  popUpWidnow  Iframe  \
0                           -1  ...           1            1       1   
1                            1  ...           1            1       1   
2                           -1  ...          -1           -1      -1   
3                            1  ...           1           -1      -1   
4                           -1  ...           1            1       1   

   age_of_domain  DNSRecord  web_traffic  Page_Rank  Google_Index  \
0              1          1            1          1            -1   
1             -1         -1            0         -1            -1   
2              1         -1            1         -1             1   
3              1         -1            1         -1             1   
4              1          1            1         -1             1   

   Links_pointing_to_page  Statistical_report  
0                       0                   1  
1                       0                   1  
2                       1                  -1  
3                       1                  -1  
4                       0                   1  

[5 rows x 31 columns]

In [4]:
# split into X and Y

ph_tr_ind = ph_tr.set_index('key')
X_train = ph_tr_ind.drop('Result', axis = 1, inplace = False)
y_train = ph_tr_ind.loc[:,['Result']]

print(X_train.shape)
print(y_train.shape)
print(y_train[y_train['Result'] == 1].shape)
print(y_train[y_train['Result'] == -1].shape)
print('=' * 20)

ph_te_ind = ph_te.set_index('key')
X_test = ph_te_ind

print(X_test.shape)

X_train.head()

(8955, 30)
(8955, 1)
(5034, 1)
(3921, 1)
(2100, 30)


having_IP  URL_Length  Shortining_Service  having_At_Symbol  \
key                                                                  
12344         -1           1                   1                 1   
12345          1           1                   1                 1   
12346          1           0                   1                 1   
12347          1           0                   1                 1   
12348          1           0                  -1                 1   

       double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  \
key                                                                 
12344                        -1             -1                 -1   
12345                         1             -1                  0   
12346                         1             -1                 -1   
12347                         1             -1                 -1   
12348                         1             -1                  1   

       SSLfinal_State  Domain_registeration_length  Favicon  ...  RightClick  \
key                                                          ...               
12344              -1                           -1        1  ...           1   
12345               1                           -1        1  ...           1   
12346              -1                           -1        1  ...           1   
12347              -1                            1        1  ...           1   
12348               1                           -1        1  ...           1   

       popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
key                                                                            
12344            1       1             -1         -1           -1         -1   
12345            1       1             -1         -1            0         -1   
12346            1       1              1         -1            1         -1   
12347            1       1             -1         -1            1         -1   
12348           -1       1             -1         -1            0         -1   

       Google_Index  Links_pointing_to_page  Statistical_report  
key                                                              
12344             1                       1                  -1  
12345             1                       1                   1  
12346             1                       0                  -1  
12347             1                      -1                   1  
12348             1                       1                   1  

[5 rows x 30 columns]

In [5]:
# split dataset into training, validation and test

from sklearn.model_selection import train_test_split

X_tr, X_cv, y_tr, y_cv = train_test_split(X_train, y_train, test_size = 0.25, random_state = 123, stratify = y_train)

print(X_tr.shape)
print(X_cv.shape)
print(y_tr.shape)
print(y_cv.shape)

X_tr.head()

(6716, 30)
(2239, 30)
(6716, 1)
(2239, 1)


having_IP  URL_Length  Shortining_Service  having_At_Symbol  \
key                                                                  
13205          1          -1                   1                 1   
16088          1          -1                   1                 1   
19242          1           1                   1                 1   
20312         -1          -1                   1                 1   
14984          1          -1                   1                 1   

       double_slash_redirecting  Prefix_Suffix  having_Sub_Domain  \
key                                                                 
13205                         1             -1                  0   
16088                         1              1                  1   
19242                         1              1                  1   
20312                         1             -1                 -1   
14984                         1             -1                 -1   

       SSLfinal_State  Domain_registeration_length  Favicon  ...  RightClick  \
key                                                          ...               
13205              -1                           -1       -1  ...          -1   
16088               1                           -1        1  ...           1   
19242               1                           -1        1  ...           1   
20312               0                            1        1  ...           1   
14984              -1                           -1       -1  ...           1   

       popUpWidnow  Iframe  age_of_domain  DNSRecord  web_traffic  Page_Rank  \
key                                                                            
13205           -1      -1             -1         -1           -1         -1   
16088            1       1              1          1            0         -1   
19242            1       1             -1          1            0          1   
20312            1       1              1          1            0         -1   
14984           -1       1             -1         -1           -1         -1   

       Google_Index  Links_pointing_to_page  Statistical_report  
key                                                              
13205             1                       0                  -1  
16088             1                       0                   1  
19242             1                       1                   1  
20312             1                       0                  -1  
14984            -1                       0                  -1  

[5 rows x 30 columns]

In [7]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(X_tr, y_tr['Result'])

RandomForestClassifier()

In [8]:
from sklearn.metrics import roc_curve, f1_score, confusion_matrix

# predict probability for validation data (for class 1)
y_cv_proba = rf.predict_proba(X_cv)[:,1:]

# find roc auc score and thresholds
y_cv_norm = [0 if y == -1 else y for y in y_cv['Result']]
fpr, tpr, thresholds = roc_curve(y_cv_norm, y_cv_proba)

# calculate g-means of each threshold
gmeans = np.sqrt(tpr * (1 - fpr))

# find best threshold using gmeans
ix = np.argmax(gmeans)
print('Best Threshold=%f, G-Mean=%.3f' % (thresholds[ix], gmeans[ix]))

# find best threshold using f1_score
f1_sc_list = []
for th in thresholds:
  y_cv_pred = [1 if p > th else 0 for p in y_cv_proba]
  f1_sc = f1_score(y_cv_norm, y_cv_pred)
  f1_sc_list.append(f1_sc)

max_f1_ix = np.argmax(f1_sc_list)
print('Best Threshold=%f, F1-Score=%.3f' % (thresholds[max_f1_ix], f1_sc_list[max_f1_ix]))

# find best threshold using J statistic
J = fpr - tpr
ix_j = np.argmax(J)
print('Best Threshold=%f, J=%.3f' % (thresholds[ix_j], J[ix_j]))

# find F1 score at best GM threshold
best_thres = thresholds[ix]
y_cv_pred_gm = [1 if p > best_thres else 0 for p in y_cv_proba]
f1_sc_gm = f1_score(y_cv_norm, y_cv_pred_gm)
print('F1-Score (GM Threshold)=%.3f' % (f1_sc_gm))

# find F1 score at best J threshold
best_thres = thresholds[ix_j]
y_cv_pred_j = [1 if p > best_thres else 0 for p in y_cv_proba]
f1_sc_j = f1_score(y_cv_norm, y_cv_pred_j)
print('F1-Score (J Threshold)=%.3f' % (f1_sc_j))

Best Threshold=0.546481, G-Mean=0.970
Best Threshold=0.422667, F1-Score=0.975
Best Threshold=2.000000, J=0.000
F1-Score (GM Threshold)=0.974
F1-Score (J Threshold)=0.000


In [9]:
# plot confusion matrix

from sklearn.metrics import confusion_matrix

# for threshold using gm
print(confusion_matrix(y_cv_norm, y_cv_pred_gm))

# for threshold using f1 score
best_thres = thresholds[max_f1_ix]
y_cv_pred_f1 = [1 if p > best_thres else 0 for p in y_cv_proba]
print(confusion_matrix(y_cv_norm, y_cv_pred_f1))

# for threshold using j matrix
print(confusion_matrix(y_cv_norm, y_cv_pred_j))

[[ 946   34]
 [  32 1227]]
[[ 927   53]
 [  11 1248]]
[[ 980    0]
 [1259    0]]


In [10]:
# generate CSV submission file

# get probabilities of class 1
y_test_proba = rf.predict_proba(X_test)[:,1:]

# get prediction using ideal threshold
thresh_used = thresholds[max_f1_ix]
y_test_pred = [1 if p > best_thres else 0 for p in y_test_proba]

print(len(y_test_proba))

df_final_test = X_test.reset_index()
df_final_test['Result'] = y_test_pred

df_submission = df_final_test.loc[:,['key','Result']]

# save in CSV

import datetime
cur_date = datetime.datetime.now()
date_str = cur_date.strftime("%Y-%m-%d-%H%M%S")

filename = './Submissions/' + date_str + '_RF_predictions_akatsuki.csv'
print(filename)
df_submission.to_csv(filename, index = False)

df_submission.head()

2100
./Submissions/2022-06-03-065254_RF_predictions_akatsuki.csv


key  Result
0  21338       1
1  21339       0
2  21340       0
3  21341       0
4  21342       1